insert into consent_customer (identifier,identifier_type) VALUES ('detteb@kunde1.no','EMAIL' );
insert into consent_customer (identifier,identifier_type) VALUES ('dettec@kunde1.no','EMAIL' );
insert into consent_customer (identifier,identifier_type) VALUES ('detted@kunde1.no','EMAIL');
insert into consent_customer (identifier,identifier_type) VALUES ('12037645131','SSN');
insert into consent_customer (identifier,identifier_type) VALUES ('12037644771','SSN');

insert into consent_channel (name) VALUES ('kunde1');
insert into consent_channel (name) VALUES ('kunde2');
insert into consent_channel (name) VALUES ('kunde3');

insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('MARKETING','Markedsf�ring','Ja, kunde1  kan bruke informasjon fra mitt kundeforhold til � skreddersy kommunikasjon og gi gode tilbud ','kunde1  �nsker � gi deg relevant kommunikasjon og gode tilbud. kunde1  kan med ditt samtykke bruke personopplysninger fra ditt kundeforhold til � gi deg relevant kommunikasjon og gode tilbud fra en. Eksempler kan v�re gratis etableringsgebyr p� l�n eller rabatt p� varekategorier du kj�per mye av. Slik markedsf�ring kan skje p� e-post, sms, telefon og i nett, og samtykket kan n�r som helst trekkes tilbake.',0,1,(select id from consent_channel where name = 'kunde1'));
insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('MARKETING_kunde2','Markedsf�ring','Ja, kunde2 Visa kan bruke informasjon fra mitt kundeforhold til � skreddersy kommunikasjon og gi gode tilbud','kunde2 Visa �nsker � gi deg relevant kommunikasjon og gode tilbud. kunde2 Visa kan med ditt samtykke bruke personopplysninger fra ditt kundeforhold til � gi deg relevant kommunikasjon og gode tilbud fra samarbeidspartnere. Eksempler kan v�re gratis etableringsgebyr p� l�n eller rabatt p� varekategorier du kj�per mye av. Slik markedsf�ring kan skje p� e-post, sms, telefon og i nett, og samtykket kan n�r som helst trekkes tilbake. kunde1  er kredittgiver for kunde2 Visa.',0,1,(select id from consent_channel where name = 'kunde2'));
insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('MARKETING_kunde3','Markedsf�ring','Ja, kunde3 Credit kan bruke informasjon fra mitt kundeforhold til � skreddersy kommunikasjon og gi gode tilbud','kunde3 Credit �nsker � gi deg relevant kommunikasjon og gode tilbud kunde3 Credit kan med ditt samtykke bruke personopplysninger fra ditt kundeforhold til � gi deg relevant kommunikasjon og gode tilbud fra samarbeidspartnere. Eksempler kan v�re gratis etableringsgebyr p� l�n eller rabatt p� varekategorier du kj�per mye av. Slik markedsf�ring kan skje p� e-post, sms, telefon og i nett, og samtykket kan n�r som helst trekkes tilbake. kunde1  er kredittgiver for kunde3 Credit.',0,1,(select id from consent_channel where name = 'kunde3'));
insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('REJECTED_CUSTOMERS','display 2','Aksepter REJECTED_CUSTOMERS','Sed ut perspiciatis unde omnis iste natus error sit voluptatem',0,1,(select id from consent_channel where name = 'kunde1'));
insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('LEGITIMATE_INTEREST','display 5','Aksepter LEGITIMATE_INTEREST','Thus makes of so lose bourns of die: the spurn not of action: who would fards of deat is question. To die, or nobles, who would by a life, the dream: ay, thers the arrows of? To dreath, them?',0,1,(select id from consent_channel where name = 'kunde1'));
insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('APPLICANT_DENIED','display 6','Aksepter APPLICANT_DENIED','decr 6',0,1,(select id from consent_channel where name = 'kunde1'));

insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('A','A 1','Aksepter A','To beart-ache of outly takes us all; and nation. To die: that pith a sea of some of greams mortal shocks thance dothere''s thus forthy takes, and may contumely, and scover''d long,',0,1,(select id from consent_channel where name = 'kunde2'));
insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('B','A 2','Aksepter B','Hints: This works best if the input is a paragraph of ordinary words with no line breaks, no tabs, and no extra spaces. Single punctuation marks (periods, commas, etc.) work well, but paired punctuation marks (quotes, parentheses, etc.) do not work well.',0,1,(select id from consent_channel where name = 'kunde2'));
insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('C','A 3','Aksepter C','Level n is based on the statistical distribution of groups of n characters.',0,1,(select id from consent_channel where name = 'kunde2'));
insert into consent_types (name,display_name,consent_text,description,consent_default_indicator,display_to_customer,consent_channel_id) VALUES ('D','do not display to customer','Aksepter D','We think that most extensible web sites use far too much FOAF, and not enough PNG.',0,0,(select id from consent_channel where name = 'kunde2'));


